language: python
python:
#  - "2.6"
  - "2.7"
# command to run tests
script:
#To run this from scratch, now do the following:
#cd clas12simulations
#if a database file exists, remove it with
#  - rm database/CLAS12OCR_DB.db
  - python2 utils/create_database.py -d 1
  - python2 client/src/SubMit.py -d 1
  - cd server
  - python2 src/Submit_batch.py -d 1
  - cd ../
  - cat database/CLAS12_OCRDB.db
#to submit to HTCondor on Submit, for example, do the following:
#python2 Submit_batch.py -s
addons:
  hosts:
    - travis.dev
