language: python
python:
#  - "2.6"
  - "2.7"
# command to run tests
script:
#To run this from scratch, now do the following:
# cd clas12simulations
#if a database file exists, remove it with
#  - rm database/CLAS12OCR_DB.db
  - python2 server/src/new_db.py
  - cd client
#  - python2 src/SubMit.py
  - cd ../server/src
  - python2 Submit_batch.py
#to submit to HTCondor on Submit, for example, do the following:
#python2 Submit_batch.py -s
